name: Deploy Vite Project to Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          

      - name: Install Dependencies
        run: npm install

      - name: Build Production Files
        run: |
          chmod -R +x node_modules/.bin/
          npm run build

      - name: Setup Pages Engine
        uses: actions/configure-pages@v4

      - name: Upload Built Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Matches your vite.config.ts outDir target perfectly
          path: './dist/public'

      - name: Deploy Live
        id: deployment
        uses: actions/deploy-pages@v4
